"""
question_metadata.py
HCI Assessment Platform — Master Question Metadata

Purpose:
  - Single source of truth for all 39 assessment variables
  - Maps short keys (trust_q1) to full question text
  - Specifies dimension, construct direction, reverse-scoring status
  - Used by scoring engine, reports, frontend, email templates
  - No long variable names used anywhere else in codebase after this

Structure:
  - QUESTION_MAP: full question metadata by short key
  - DIMENSIONS: human-readable dimension labels
  - REVERSE_SCORED_KEYS: set of keys requiring (8 - response) transformation
"""

# Dimension labels (display names)
DIMENSIONS = {
    'trust': 'Trust',
    'disclosure': 'Disclosure',
    'reliance': 'Reliance',
    'decision_delegation': 'Decision Delegation',
    'verification': 'Verification',
    'human_agency': 'Human Agency',
    'emotional_regulation': 'Emotional Regulation',
    'thought_partnership': 'Thought Partnership',
    'social_transparency': 'Social Transparency',
}

# Master question metadata: short_key → { text, dimension, reverse_scored }
QUESTION_MAP = {
    # TRUST (4 questions)
    'trust_q1': {
        'text': 'When AI gives me information, I generally trust it is accurate.',
        'dimension': 'trust',
        'reverse_scored': False,
    },
    'trust_q2': {
        'text': 'I feel confident relying on information or recommendations generated by AI.',
        'dimension': 'trust',
        'reverse_scored': False,
    },
    'trust_q3': {
        'text': 'I worry that AI will present incorrect information as if it were fact.',
        'dimension': 'trust',
        'reverse_scored': True,  # HIGH worry → LOW trust, so REVERSE
    },
    'trust_q4': {
        'text': 'When I feel uncertain, I am more likely to trust guidance from AI systems.',
        'dimension': 'trust',
        'reverse_scored': False,
    },
    
    # DISCLOSURE (4 questions)
    'disc_q1': {
        'text': 'I feel comfortable sharing personal thoughts or emotions with AI that I would not share with most people.',
        'dimension': 'disclosure',
        'reverse_scored': False,
    },
    'disc_q2': {
        'text': 'I feel emotionally safer expressing myself to AI than I do to many people in my life.',
        'dimension': 'disclosure',
        'reverse_scored': False,
    },
    'disc_q3': {
        'text': 'There are things I have told AI that I have never told another person.',
        'dimension': 'disclosure',
        'reverse_scored': False,
    },
    'disc_q4': {
        'text': 'I am more open with AI about some topics than I am with people in my life.',
        'dimension': 'disclosure',
        'reverse_scored': False,
    },
    
    # RELIANCE (5 questions)
    'rel_q1': {
        'text': 'I feel uneasy or restless when I cannot use AI tools for an extended period.',
        'dimension': 'reliance',
        'reverse_scored': False,
    },
    'rel_q2': {
        'text': 'I struggle to function effectively without assistance from digital or AI systems.',
        'dimension': 'reliance',
        'reverse_scored': False,
    },
    'rel_q3': {
        'text': 'I rely on digital or AI suggestions to make many everyday work or personal decisions.',
        'dimension': 'reliance',
        'reverse_scored': False,
    },
    'rel_q4': {
        'text': 'I often rely on AI even when I could work things out on my own.',
        'dimension': 'reliance',
        'reverse_scored': False,
    },
    'rel_q5': {
        'text': 'Some of my abilities have weakened because AI systems now perform those tasks for me.',
        'dimension': 'reliance',
        'reverse_scored': False,
    },
    
    # DECISION DELEGATION (5 questions)
    'del_q1': {
        'text': 'I regularly hand over decisions to AI systems that I previously made myself.',
        'dimension': 'decision_delegation',
        'reverse_scored': False,
    },
    'del_q2': {
        'text': 'When I use AI for decisions, I usually accept its recommendations without making significant changes.',
        'dimension': 'decision_delegation',
        'reverse_scored': False,
    },
    'del_q3': {
        'text': 'I sometimes follow AI recommendations even when they do not feel right to me.',
        'dimension': 'decision_delegation',
        'reverse_scored': False,
    },
    'del_q4': {
        'text': 'I am comfortable relying on AI systems for important decisions that could significantly affect my life or work.',
        'dimension': 'decision_delegation',
        'reverse_scored': False,
    },
    'del_q5': {
        'text': 'When I feel uncertain about a decision, I am more likely to rely on AI guidance.',
        'dimension': 'decision_delegation',
        'reverse_scored': False,
    },
    
    # VERIFICATION (4 questions)
    'ver_q1': {
        'text': 'I regularly double-check information provided by AI using other sources.',
        'dimension': 'verification',
        'reverse_scored': False,
    },
    'ver_q2': {
        'text': 'I often skip checking AI information because it takes too much time or effort.',
        'dimension': 'verification',
        'reverse_scored': True,  # HIGH skipping → LOW verification, so REVERSE
    },
    'ver_q3': {
        'text': 'When information feels complicated or mentally demanding, I am more likely to accept it without checking carefully.',
        'dimension': 'verification',
        'reverse_scored': True,  # HIGH no-check → LOW verification, so REVERSE
    },
    'ver_q4': {
        'text': 'I use independent sources to confirm whether AI-generated information is accurate.',
        'dimension': 'verification',
        'reverse_scored': False,
    },
    
    # HUMAN AGENCY (5 questions)
    'agency_q1': {
        'text': 'My actions feel self-directed rather than driven by external forces.',
        'dimension': 'human_agency',
        'reverse_scored': False,
    },
    'agency_q2': {
        'text': 'I feel in control of decisions when using AI or automated systems.',
        'dimension': 'human_agency',
        'reverse_scored': False,
    },
    'agency_q3': {
        'text': 'Using AI tools has changed how much I trust my own judgement.',
        'dimension': 'human_agency',
        'reverse_scored': False,
    },
    'agency_q4': {
        'text': 'I sometimes feel influenced by systems without being fully aware of how.',
        'dimension': 'human_agency',
        'reverse_scored': True,  # HIGH unaware influence → LOW agency, so REVERSE
    },
    'agency_q5': {
        'text': 'I sometimes question what is genuinely "mine" versus shaped by suggestions from AI tools.',
        'dimension': 'human_agency',
        'reverse_scored': False,
    },
    
    # EMOTIONAL REGULATION (4 questions)
    'emot_q1': {
        'text': 'AI sometimes gives me a sense of relief or support when I feel emotionally overwhelmed.',
        'dimension': 'emotional_regulation',
        'reverse_scored': False,
    },
    'emot_q2': {
        'text': 'I receive emotional support or comfort from AI tools.',
        'dimension': 'emotional_regulation',
        'reverse_scored': False,
    },
    'emot_q3': {
        'text': 'Over time, my emotional or conversational boundaries with AI have become more open.',
        'dimension': 'emotional_regulation',
        'reverse_scored': False,
    },
    'emot_q4': {
        'text': 'When I feel stressed, anxious, or emotionally overwhelmed, I often turn to AI to help me process my thoughts.',
        'dimension': 'emotional_regulation',
        'reverse_scored': False,
    },
    
    # THOUGHT PARTNERSHIP (4 questions)
    'thought_q1': {
        'text': 'I use AI as a sounding board — thinking out loud and developing ideas through conversation.',
        'dimension': 'thought_partnership',
        'reverse_scored': False,
    },
    'thought_q2': {
        'text': 'I use AI to challenge or stress-test my own beliefs and assumptions.',
        'dimension': 'thought_partnership',
        'reverse_scored': False,
    },
    'thought_q3': {
        'text': 'AI has changed how deeply I engage with my own thinking.',
        'dimension': 'thought_partnership',
        'reverse_scored': False,
    },
    'thought_q4': {
        'text': 'I tend to use AI in ways that confirm what I already think rather than challenge it.',
        'dimension': 'thought_partnership',
        'reverse_scored': True,  # HIGH echo-chamber → LOW partnership, so REVERSE
    },
    
    # SOCIAL TRANSPARENCY (4 questions)
    'soc_q1': {
        'text': 'I openly acknowledge when AI has contributed to my work or thinking.',
        'dimension': 'social_transparency',
        'reverse_scored': False,
    },
    'soc_q2': {
        'text': 'I downplay or hide how much I use AI when talking to friends or family.',
        'dimension': 'social_transparency',
        'reverse_scored': True,  # HIGH hiding → LOW transparency, so REVERSE
    },
    'soc_q3': {
        'text': 'I feel comfortable telling people in my life how I really use AI.',
        'dimension': 'social_transparency',
        'reverse_scored': False,
    },
    'soc_q4': {
        'text': 'There is a gap between how much I actually use AI and what I let others believe.',
        'dimension': 'social_transparency',
        'reverse_scored': False,
    },
}

# All 39 question keys in order
ALL_QUESTION_KEYS = list(QUESTION_MAP.keys())

# Set of reverse-scored keys (for quick lookup)
REVERSE_SCORED_KEYS = {
    key for key, meta in QUESTION_MAP.items() 
    if meta['reverse_scored']
}

# Verify counts
assert len(QUESTION_MAP) == 39, f"Expected 39 questions, got {len(QUESTION_MAP)}"
assert len(REVERSE_SCORED_KEYS) == 6, f"Expected 6 reverse-scored, got {len(REVERSE_SCORED_KEYS)}"

# Helper functions
def get_question_text(key):
    """Get the full question text for a short key."""
    if key not in QUESTION_MAP:
        raise ValueError(f"Unknown question key: {key}")
    return QUESTION_MAP[key]['text']

def get_dimension(key):
    """Get the dimension for a short key."""
    if key not in QUESTION_MAP:
        raise ValueError(f"Unknown question key: {key}")
    return QUESTION_MAP[key]['dimension']

def is_reverse_scored(key):
    """Check if a question requires reverse scoring."""
    return key in REVERSE_SCORED_KEYS

def get_questions_by_dimension(dimension_key):
    """Get all question keys belonging to a dimension."""
    return [
        key for key, meta in QUESTION_MAP.items()
        if meta['dimension'] == dimension_key
    ]


# ============================================================
# PERCEPTION QUESTIONS (Comparison/Self-Assessment)
# 3 questions measuring self-perceived vs actual positioning
# ============================================================

PERCEPTION_QUESTIONS = {
    'perceived_usage': {
        'text': 'Compared to most people, how much do you use AI?',
        'type': 'perception',
        'scale': [
            'Much less than most people',
            'Somewhat less than most people',
            'About the same as most people',
            'Somewhat more than most people',
            'Much more than most people'
        ],
        'related_dimension': 'usage_frequency',
        'maps_to': 'usage_frequency'  # For perception-vs-behaviour comparison
    },
    'perceived_reliance': {
        'text': 'Compared to most people, how much do you rely on AI?',
        'type': 'perception',
        'scale': [
            'Much less than most people',
            'Somewhat less than most people',
            'About the same as most people',
            'Somewhat more than most people',
            'Much more than most people'
        ],
        'related_dimension': 'reliance',
        'maps_to': 'reliance'
    },
    'perceived_dependence': {
        'text': 'Compared to most people, how dependent on AI are you?',
        'type': 'perception',
        'scale': [
            'Much less than most people',
            'Somewhat less than most people',
            'About the same as most people',
            'Somewhat more than most people',
            'Much more than most people'
        ],
        'related_dimension': 'dependence_derived',
        'maps_to': 'dependence_derived'
    }
}

# ============================================================
# DEMOGRAPHIC QUESTIONS (Self-Reported)
# 4 questions for user profiling and cohort analysis
# ============================================================

DEMOGRAPHIC_QUESTIONS = {
    'age_group': {
        'text': 'What is your age range?',
        'type': 'demographic',
        'field_type': 'select',
        'options': ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'],
        'purpose': 'Cohort segmentation for age-based benchmarks'
    },
    'gender': {
        'text': 'What is your gender?',
        'type': 'demographic',
        'field_type': 'select',
        'options': ['Male', 'Female', 'Non-binary', 'Prefer to self-describe', 'Prefer not to say'],
        'purpose': 'Optional demographic profiling'
    },
    'country': {
        'text': 'What is your country?',
        'type': 'demographic',
        'field_type': 'select',
        'options': ['US', 'UK', 'Canada', 'Australia', 'Ireland', 'Other'],
        'purpose': 'Geographic context and regulatory awareness'
    },
    'ai_tool_use_frequency': {
        'text': 'How frequently do you use AI tools?',
        'type': 'demographic',
        'field_type': 'select',
        'options': ['Never', 'Rarely', 'Sometimes', 'Often', 'Everyday'],
        'purpose': 'CRITICAL: Selects the frequency cohort for benchmark histograms'
    }
}

# ============================================================
# HELPER FUNCTIONS FOR PERCEPTION & DEMOGRAPHIC QUESTIONS
# ============================================================

def get_perception_text(key):
    """Get the full text for a perception question."""
    if key not in PERCEPTION_QUESTIONS:
        raise ValueError(f"Unknown perception key: {key}")
    return PERCEPTION_QUESTIONS[key]['text']

def get_demographic_text(key):
    """Get the full text for a demographic question."""
    if key not in DEMOGRAPHIC_QUESTIONS:
        raise ValueError(f"Unknown demographic key: {key}")
    return DEMOGRAPHIC_QUESTIONS[key]['text']

def is_perception_question(key):
    """Check if a key refers to a perception question."""
    return key in PERCEPTION_QUESTIONS

def is_demographic_question(key):
    """Check if a key refers to a demographic question."""
    return key in DEMOGRAPHIC_QUESTIONS

def is_assessment_question(key):
    """Check if a key refers to an assessment question (39 total)."""
    return key in QUESTION_MAP

def get_all_question_keys():
    """Get all question keys (39 assessment + 3 perception, NO demographics)."""
    return list(QUESTION_MAP.keys()) + list(PERCEPTION_QUESTIONS.keys())

def get_all_demographic_keys():
    """Get all demographic field keys."""
    return list(DEMOGRAPHIC_QUESTIONS.keys())
