"""
report_templates.py

Deterministic HCI report content.

Purpose
-------
This file contains pre-written/static report content only.

It is for content that should NOT be generated by Claude:
- Opening statement
- Dimension definitions
- Positioning language
- Section 3 light templates
- Section 9 What To Protect templates
- Section 10 strengths/monitoring template assets
- Section 11 Next Steps

Claude should only write sections explicitly marked API CALL in the locked report spec.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------
# Locked dimension content
# ---------------------------------------------------------------------

DIMENSION_ORDER = [
    "reliance",
    "trust",
    "verification",
    "decision_delegation",
    "human_agency",
    "disclosure",
    "emotional_regulation",
    "thought_partnership",
    "social_transparency",
]

DIMENSION_LABELS = {
    "reliance": "Reliance",
    "trust": "Trust",
    "verification": "Verification",
    "decision_delegation": "Decision Delegation",
    "human_agency": "Human Agency",
    "emotional_regulation": "Emotional Regulation",
    "disclosure": "Disclosure",
    "thought_partnership": "Thought Partnership",
    "social_transparency": "Social Transparency",
}

DIMENSION_DEFINITIONS = {
    "reliance": "How much you depend on AI for thinking and functioning",
    "trust": "How much you believe AI outputs are accurate",
    "verification": "How often you check AI outputs before using them",
    "decision_delegation": "How much you hand over decisions to AI",
    "human_agency": "How much control you maintain over your decisions",
    "emotional_regulation": "Whether you turn to AI for emotional support",
    "disclosure": "How much personal information you share with AI",
    "thought_partnership": "How much you use AI as a thinking partner",
    "social_transparency": "How openly you discuss your AI use with others",
}


# ---------------------------------------------------------------------
# Positioning language
# ---------------------------------------------------------------------

def ordinal(n: Any) -> str:
    try:
        n = int(round(float(n)))
    except Exception:
        n = 0
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def percentile_position(percentile: Any) -> str:
    try:
        p = int(round(float(percentile)))
    except Exception:
        p = 50

    if p >= 96:
        return "exceptionally high"
    if p >= 86:
        return "notably high"
    if p >= 71:
        return "above population centre"
    if p >= 41:
        return "near population centre"
    if p >= 26:
        return "below population centre"
    if p >= 11:
        return "notably low"
    return "exceptionally low"


def protect_position(percentile: Any) -> str:
    try:
        p = int(round(float(percentile)))
    except Exception:
        p = 50

    if p >= 71:
        return "at the high end"
    if p >= 41:
        return "in the middle"
    return "at the low end"


def plain_percentile_score(percentile: Any) -> str:
    try:
        p = int(round(float(percentile)))
    except Exception:
        p = 50
    return f"Higher than {p} of 100 people"


# ---------------------------------------------------------------------
# Opening static content
# ---------------------------------------------------------------------

OPENING_STATEMENT = """You are uniquely positioned in how you relate to AI. Your profile reflects how you currently engage with AI systems — based on your responses benchmarked against 10,500 participants across 21 research studies.

Use this report to understand your pattern:

• Understand what's distinctive about how you work with AI
• Notice where you're typical and where you stand out
• Explore what's worth protecting as your use evolves
• Make conscious choices about your relationship with AI going forward"""


# ---------------------------------------------------------------------
# Section 3: How Typical templates
# ---------------------------------------------------------------------

SECTION_3_TEMPLATES = {
    "distinctive_high": "You sit {position} on {dimension}. This means {plain_meaning}",
    "distinctive_low": "You sit {position} on {dimension}. This means {plain_meaning}",
    "typical": "You sit in the middle range on {dimension}. This means you move through this area without standing out sharply from the benchmark population.",
}

DIMENSION_PLAIN_MEANINGS = {
    "reliance": {
        "high": "AI is deeply integrated into how you work, think, or function day to day.",
        "low": "AI is not central to how you function, even if you use it in specific situations.",
        "typical": "your level of AI dependence is close to the population centre.",
    },
    "trust": {
        "high": "you tend to approach AI outputs with a relatively high level of confidence.",
        "low": "you retain more caution than most people before accepting AI outputs.",
        "typical": "your trust in AI is balanced rather than unusually high or low.",
    },
    "verification": {
        "high": "checking remains a strong part of your AI process.",
        "low": "you may move through AI outputs with less checking than most people.",
        "typical": "your checking rhythm is close to the population centre.",
    },
    "decision_delegation": {
        "high": "AI plays a larger role in decisions that many people still keep mostly to themselves.",
        "low": "you keep decision authority closer to yourself than most people.",
        "typical": "your level of decision handover is close to the population centre.",
    },
    "human_agency": {
        "high": "you retain a strong sense of authorship and control while using AI.",
        "low": "you may experience less direct ownership over decisions or thinking processes involving AI.",
        "typical": "your sense of agency sits close to the population centre.",
    },
    "disclosure": {
        "high": "you share more personal material with AI than most people.",
        "low": "you keep more personal material away from AI than most people.",
        "typical": "your disclosure level is close to the population centre.",
    },
    "emotional_regulation": {
        "high": "AI plays a meaningful role in emotional support, relief, or processing.",
        "low": "AI is not a major emotional support channel for you.",
        "typical": "your emotional use of AI sits close to the population centre.",
    },
    "thought_partnership": {
        "high": "AI is strongly integrated into how you develop, test, and refine ideas.",
        "low": "AI is less central to your thinking process than it is for many people.",
        "typical": "your use of AI as a thinking partner is close to the population centre.",
    },
    "social_transparency": {
        "high": "you are more open than most people about how you use AI.",
        "low": "you are more private than most people about your AI use.",
        "typical": "your openness about AI use sits close to the population centre.",
    },
}


def typicality_sentence(dimension: str, percentile: Any) -> str:
    pos = percentile_position(percentile)
    try:
        p = int(round(float(percentile)))
    except Exception:
        p = 50

    if p >= 71:
        tone = "high"
        template = SECTION_3_TEMPLATES["distinctive_high"]
    elif p <= 40:
        tone = "low"
        template = SECTION_3_TEMPLATES["distinctive_low"]
    else:
        tone = "typical"
        template = SECTION_3_TEMPLATES["typical"]

    return template.format(
        position=pos,
        dimension=DIMENSION_LABELS.get(dimension, dimension).lower(),
        plain_meaning=DIMENSION_PLAIN_MEANINGS.get(dimension, {}).get(tone, ""),
    )


# ---------------------------------------------------------------------
# Section 9: What To Protect locked templates
# ---------------------------------------------------------------------

WHAT_TO_PROTECT_TEMPLATES = {
    "verification": {
        "title": "What to Notice: When Verification Becomes Tiring",
        "dimension_label": "Verification",
        "intro": "Most people verify AI outputs before acting. But the research reveals something important: constant verification can become cognitively costly, and many people move toward selective checking — checking only what feels high-risk or important.",
        "watch": [
            "Noticing yourself checking less than usual",
            "Feeling relief or efficiency when you skip verification",
            "Finding it hard to care whether an output is accurate",
            "Moving from “verify everything” to “verify selectively” without realizing it",
        ],
        "research": "Verification fatigue is real and common. It is not laziness — it is the cost of constant cognitive effort. The question worth noticing is whether your verification rhythm serves your needs, or whether you are rationing it because it is exhausting.",
        "closing": "You decide what level of verification matters to you.",
    },
    "human_agency": {
        "title": "What to Notice: When Drift Happens Without You Choosing It",
        "dimension_label": "Human Agency",
        "intro": "Research shows an interesting contrast: at the identity level, agency is often strong — people retain a clear sense of responsibility for their decisions. But at the process level, subtle steering can still happen through AI suggestions, defaults, and framing.",
        "watch": [
            "Accepting AI suggestions without thinking them through first",
            "Using AI defaults instead of customizing your approach",
            "Realizing you have not actually made a decision yourself in days",
            "Noticing AI’s framing has become your first instinct",
            "Finding it harder to develop your own position before consulting AI",
        ],
        "research": "Drift happens through convenience, not collapse. You are not losing agency overnight — you are losing it incrementally through small moments where the path of least resistance happens to align with what AI suggests.",
        "closing": "You decide if this matters to you.",
    },
    "emotional_regulation": {
        "title": "What to Notice: If Emotional Reliance Becomes Substitution",
        "dimension_label": "Emotional Regulation",
        "intro": "This is one of the most live tensions in HCI’s research. Many people still believe that only humans can truly meet emotional needs, while a growing share already use AI for relief, support, or emotional processing.",
        "watch": [
            "Turning to AI before turning to people when you are struggling",
            "Preferring AI conversations to human ones for processing difficult feelings",
            "Finding it harder to sit with discomfort without AI input",
            "Noticing you are more open with AI about emotions than with people you trust",
            "Realizing emotional support from AI feels more available than human support",
        ],
        "research": "This is not inherently a problem. For some people, AI offers a genuinely safe space that human relationships do not. But it is worth noticing the difference between AI as a supplement to human connection and AI as a replacement for it.",
        "closing": "You decide if emotional support from AI is right for you.",
    },
    "thought_partnership": {
        "title": "What to Notice: When Thinking With AI Becomes Thinking For You",
        "dimension_label": "Thought Partnership",
        "intro": "AI works best as a thinking partner — something to develop ideas with, not instead of your own thinking. The important distinction is whether AI is challenging your thinking or quietly replacing it.",
        "watch": [
            "Defaulting to AI’s framing instead of developing your own position first",
            "Struggling to think independently when AI is not available",
            "Realizing AI’s suggestions have become your first instinct, not your second opinion",
            "Finding it hard to disagree with AI once it has stated a position",
            "Noticing you use AI to avoid the discomfort of thinking through hard problems alone",
        ],
        "research": "Genuine partnership requires you to know what you think before you ask AI. The people who maintain clear authorship are the ones who use AI to challenge their thinking, not replace it. Values clarity is what keeps that distinction alive.",
        "closing": "You decide if this matters to you.",
    },
}


# ---------------------------------------------------------------------
# Section 10: If Nothing Changes deterministic assets
# ---------------------------------------------------------------------

STRENGTH_DEEPENING_COPY = {
    "reliance": {
        "what_deepening_looks_like": "AI becoming a more natural first stop for work, decision support, or cognitive offloading.",
        "early_signal": "Noticing more tasks feel slower or harder without AI.",
    },
    "trust": {
        "what_deepening_looks_like": "Moving through AI outputs with less friction because confidence has become part of the workflow.",
        "early_signal": "Accepting outputs quickly because past experience has made AI feel reliable.",
    },
    "verification": {
        "what_deepening_looks_like": "A more disciplined checking rhythm, especially around high-stakes or unfamiliar information.",
        "early_signal": "Keeping independent confirmation as a normal part of AI use.",
    },
    "decision_delegation": {
        "what_deepening_looks_like": "More decisions being shaped by AI recommendations before you make a final call.",
        "early_signal": "Noticing AI has become part of the decision process by default.",
    },
    "human_agency": {
        "what_deepening_looks_like": "Clearer authorship over decisions even when AI contributes to the process.",
        "early_signal": "Knowing where AI input ends and your own judgment begins.",
    },
    "disclosure": {
        "what_deepening_looks_like": "Greater comfort using AI as a private space for thoughts, feelings, or personal concerns.",
        "early_signal": "Sharing material with AI before sharing it with people.",
    },
    "emotional_regulation": {
        "what_deepening_looks_like": "AI becoming a more available source of relief, emotional processing, or conversational support.",
        "early_signal": "Turning to AI quickly when stress, uncertainty, or overwhelm appears.",
    },
    "thought_partnership": {
        "what_deepening_looks_like": "More fluent idea development, faster iteration, and deeper exploration of complex thoughts.",
        "early_signal": "AI becoming part of how you think through almost anything difficult.",
    },
    "social_transparency": {
        "what_deepening_looks_like": "More ease naming when and how AI is involved in your work or personal life.",
        "early_signal": "Discussing AI use openly without needing to hide or justify it.",
    },
}

MONITORING_COPY = {
    "verification": {
        "why_monitor": "Verification is one of the places where fatigue can change behaviour quietly. If usage increases, the pressure is often not whether people know they should check, but whether checking feels worth the effort.",
        "early_sign": "Noticing yourself checking less, or feeling relief when you skip it.",
    },
    "reliance": {
        "why_monitor": "Reliance tends to deepen as AI becomes more embedded in daily functioning. This is not automatically a problem, but it is one of the clearest places where baseline habits can shift.",
        "early_sign": "Struggling to function without AI, or avoiding tasks that require independent thinking.",
    },
    "human_agency": {
        "why_monitor": "Agency can remain strong at the identity level while the process of decision-making still drifts through suggestions, defaults, and convenience.",
        "early_sign": "Using AI’s framing before developing your own position.",
    },
    "emotional_regulation": {
        "why_monitor": "Emotional use can become more available than human support because AI is instant, responsive, and private. The important distinction is whether it supplements or substitutes for human connection.",
        "early_sign": "Turning to AI before people whenever something feels emotionally difficult.",
    },
    "thought_partnership": {
        "why_monitor": "Thought partnership is powerful when it develops your thinking. It is worth watching when it starts becoming the place where thinking begins, ends, and is resolved for you.",
        "early_sign": "Finding it difficult to form your own view before asking AI.",
    },
}


# ---------------------------------------------------------------------
# Section 11: Next Steps locked content
# ---------------------------------------------------------------------

NEXT_STEPS = [
    {
        "title": "Step 1: Test This Report With Your AI",
        "body": [
            "Upload this full report to whichever AI you use most.",
            'Ask it: “Does this report ring true to how we work together? Where does it match your sense of how I use you? Where does it miss?”',
            "Listen for where it confirms vs. where it challenges. This conversation will deepen your clarity about your actual pattern.",
            "A note: Your data stays with you. Nothing about this conversation returns to HCI.",
        ],
    },
    {
        "title": "What This Awareness Does",
        "body": [
            "Knowing your pattern is the foundation for clarity. And clarity is what lets you make intentional choices about your boundaries with AI.",
            "This report shows you where you sit — how you use AI, what you rely on it for, where you are distinctive, where you are typical. That positioning is neutral. What matters is what you do with it.",
            "The people who flourish with AI are the ones who stay aware of their own pattern and adjust their relationship as it evolves. Not through willpower or rules, but through genuine understanding of what serves them.",
        ],
    },
    {
        "title": "Stay Within Your Boundaries",
        "body": [
            "Return to this assessment periodically — quarterly, annually, or whenever your relationship with AI feels like it is shifting significantly.",
            "Retesting lets you notice what has actually changed in your pattern, not what you think has changed. It is the clearest way to stay within the boundaries that help you flourish.",
        ],
    },
    {
        "title": "This Report As A Mirror",
        "body": [
            "This report is a mirror. What it shows is real — your positioning in a benchmark population, your rare combinations, your observable patterns.",
            "What you do with that clarity is entirely yours.",
        ],
    },
]
