-- HCI Assessment Platform — Supabase Schema
-- Run this SQL in Supabase SQL Editor to set up the database
-- Date: June 25, 2026

-- ============================================================
-- assessment_responses TABLE
-- ============================================================
-- Stores all assessment submissions, scores, and premium report data
-- UNIQUE constraint on session_id ensures no duplicates on upsert

CREATE TABLE IF NOT EXISTS assessment_responses (
  -- Identifiers
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  session_id TEXT UNIQUE NOT NULL,
  
  -- Assessment Data
  responses JSONB NOT NULL,                    -- Raw 39 question responses (1-7 scale)
  demographics JSONB NOT NULL,                 -- Age, gender, country, frequency
  
  -- Scoring Results
  full_results JSONB,                          -- Complete output from scoring_engine
                                               -- Includes: dimension_scores, perception_gaps, rare_combinations
  
  -- Contact & Consent
  report_email TEXT,                           -- Email for report delivery
  consent BOOLEAN DEFAULT FALSE,               -- Research consent checkbox
  consent_timestamp TEXT,                      -- ISO timestamp of consent
  
  -- Payment Status
  paid BOOLEAN DEFAULT FALSE,                  -- Has payment been processed?
  paid_at TIMESTAMP,                           -- When was payment confirmed?
  stripe_session_id TEXT,                      -- Stripe checkout session ID (for reference)
  
  -- Report Data (Cached)
  report_html JSONB,                           -- Full premium report (cached to prevent regeneration)
  report_pdf_url TEXT,                         -- URL to PDF in Supabase Storage
  premium_report JSONB,                        -- Alternative field name (for compatibility)
  
  -- Percentiles & Analysis (may be separate or in full_results)
  percentiles JSONB,                           -- Question-level percentiles
  perception_gaps JSONB,                       -- Perception gap analysis
  patterns JSONB,                              -- Rare combinations and patterns
  
  -- Metadata
  report_generated_at TIMESTAMP,               -- When premium report was generated
  
  -- Timestamps
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- INDEXES for Common Queries
-- ============================================================
-- Speed up lookups by session_id (most common query)
CREATE INDEX IF NOT EXISTS idx_assessment_responses_session_id 
  ON assessment_responses(session_id);

-- Speed up lookups by paid status (for admin queries)
CREATE INDEX IF NOT EXISTS idx_assessment_responses_paid 
  ON assessment_responses(paid);

-- Speed up lookups by email (for delivery retries)
CREATE INDEX IF NOT EXISTS idx_assessment_responses_email 
  ON assessment_responses(report_email);

-- Speed up lookups by creation date (for analytics)
CREATE INDEX IF NOT EXISTS idx_assessment_responses_created 
  ON assessment_responses(created_at);

-- ============================================================
-- CONSTRAINTS
-- ============================================================
-- session_id must be unique (enforced at table level above)
-- This enables UPSERT: INSERT ... ON CONFLICT(session_id) DO UPDATE

-- ============================================================
-- NOTES FOR DEVELOPERS
-- ============================================================
-- 
-- UPSERT Pattern (used in supabase_client.py):
--   INSERT INTO assessment_responses (session_id, responses, demographics, ...)
--   VALUES (...)
--   ON CONFLICT(session_id) DO UPDATE SET
--     responses = EXCLUDED.responses,
--     demographics = EXCLUDED.demographics,
--     ...
--     updated_at = CURRENT_TIMESTAMP;
--
-- This ensures:
--   - First POST /score creates new row
--   - Result page refresh updates same row (no duplicates)
--   - POST /premium updates same row with paid status and report
--
-- JSONB Storage:
--   - responses: {trust_q1: 5, trust_q2: 6, ..., perceived_usage: "..."}
--   - demographics: {age_group: "25-34", gender: "Woman", country: "UK", ...}
--   - full_results: {dimension_scores: {...}, perception_gaps: [...], ...}
--     (output from scoring_engine.py)
--   - report_html: {dashboard: "...", section1: "...", ...}
--     (output from report_generator.py, stored as JSON for caching)
--
-- Supabase Storage:
--   - PDFs are stored in bucket "reports" with path: reports/{session_id}.pdf
--   - report_pdf_url contains the public URL to access the PDF
--
-- All timestamps are UTC ISO 8601 format for consistency
